//! Chemistry related constants

pub const absolute_zero: f64 = -273.15; // [°C]
pub const avogadros_number: f64 = 6.022e23; // [molecules/mol]
pub const boltzmanns_constant: f64 = 1.380e-23; // [J/K * molecule]
pub const steffan_boltzmann_constant: f64 = 5.670e-8 ; // [W/m² * K⁴]
pub const universal_gas_constant: f64 = 8.31434e3; // [J/kmol * K]
pub const normal_atmospheric_pressure: f64 = 101325.0; // [N/m²]

/// at 0 °C and 1 atm
pub enum StateOfMatter {
    Solid,
    Liquid,
    Gas,
    Unknown,
}

pub enum SubCategory {
    AlkaliMetal,
    AlkalineEarthMetal,
    Lanthanide,
    Actinide,
    TransitionMetal,
    PostTransitionMetal,
    Metalloid,
    PolyatomicNonMetal,
    DiatomicNonMetal,
    NobleGas,
    Unknown,
}

pub struct AtomInfo {
    pub name: &'static str,
    pub full_name: &'static str,
    pub atomic_number: u32,
    pub group: u32,
    pub period: u8,
    /// [g/cm³]
    pub density: f64,
    /// [K]
    pub melt: Option<f64>,
    /// [K]
    pub boil: Option<f64>,
    pub electronegativity: Option<f64>,
    /// [J/(g*K)]
    pub heat_capacity: Option<f64>,
    /// [mg/kg]
    pub abundance: f64,
    pub number_of_neutrons: u32,
    pub mass: f64, // https://en.wikipedia.org/wiki/Relative_atomic_mass
    pub state_of_matter: StateOfMatter,
    pub sub_category: SubCategory,
    // A lot of more stuff to be added...
}

pub const atom_h: AtomInfo = AtomInfo {
    name: "H",
    full_name: "Hydrogen",
    atomic_number: 1,
    group: 1,
    period: 1,
    density: 0.00008988,
    melt: Some(14.01),
    boil: Some(20.28),
    electronegativity: Some(2.20),
    heat_capacity: Some(14.304),
    abundance: 1400.0,
    number_of_neutrons: 0,
    mass: 1.008,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_he: AtomInfo = AtomInfo {
    name: "He",
    full_name: "Helium",
    atomic_number: 2,
    group: 18,
    period: 1,
    density: 0.0001785,
    melt: Some(0.95),
    boil: Some(4.22),
    electronegativity: None,
    heat_capacity: Some(5.193),
    abundance: 0.008,
    number_of_neutrons: 2,
    mass: 4.0026022,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};


pub const atom_li: AtomInfo = AtomInfo {
    name: "Li",
    full_name: "Lithium",
    atomic_number: 3,
    group: 1,
    period: 2,
    density: 0.534,
    melt: Some(453.69),
    boil: Some(1560.0),
    electronegativity: Some(0.98),
    heat_capacity: Some(3.582),
    abundance: 20.0,
    number_of_neutrons: 4,
    mass: 6.94,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_be: AtomInfo = AtomInfo {
    name: "Be",
    full_name: "Beryllium",
    atomic_number: 4,
    group: 2,
    period: 2,
    density: 1.85,
    melt: Some(1560.0),
    boil: Some(2742.0),
    electronegativity: Some(1.57),
    heat_capacity: Some(1.825),
    abundance: 2.8,
    number_of_neutrons: 5,
    mass: 9.0121831,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkalineEarthMetal,
};

pub const atom_b: AtomInfo = AtomInfo {
    name: "B",
    full_name: "Boron",
    atomic_number: 5,
    group: 13,
    period: 2,
    density: 2.34,
    melt: Some(2349.0),
    boil: Some(4200.0),
    electronegativity: Some(2.04),
    heat_capacity: Some(1.026),
    abundance: 10.0,
    number_of_neutrons: 6,
    mass: 10.81,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_c: AtomInfo = AtomInfo {
    name: "C",
    full_name: "Carbon",
    atomic_number: 6,
    group: 14,
    period: 2,
    density: 2.267,
    melt: Some(3800.0),
    boil: Some(4300.0),
    electronegativity: Some(2.55),
    heat_capacity: Some(0.709),
    abundance: 200.0,
    number_of_neutrons: 6,
    mass: 12.011,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PolyatomicNonMetal,
};

pub const atom_n: AtomInfo = AtomInfo {
    name: "N",
    full_name: "Nitrogen",
    atomic_number: 7,
    group: 15,
    period: 2,
    density: 0.0012506,
    melt: Some(63.15),
    boil: Some(77.36),
    electronegativity: Some(3.04),
    heat_capacity: Some(1.04),
    abundance: 19.0,
    number_of_neutrons: 7,
    mass: 14.007,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_o: AtomInfo = AtomInfo {
    name: "O",
    full_name: "Oxygen",
    atomic_number: 8,
    group: 16,
    period: 2,
    density: 0.001429,
    melt: Some(54.36),
    boil: Some(90.20),
    electronegativity: Some(3.44),
    heat_capacity: Some(0.918),
    abundance: 46100.00,
    number_of_neutrons: 8,
    mass: 15.999,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_f: AtomInfo = AtomInfo {
    name: "F",
    full_name: "Fluorine",
    atomic_number: 9,
    group: 17,
    period: 2,
    density: 0.001696,
    melt: Some(53.53),
    boil: Some(85.03),
    electronegativity: Some(3.98),
    heat_capacity: Some(0.824),
    abundance: 585.0,
    number_of_neutrons: 10,
    mass: 18.998403163,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_ne: AtomInfo = AtomInfo {
    name: "Ne",
    full_name: "Neon",
    atomic_number: 10,
    group: 18,
    period: 2,
    density: 0.0008999,
    melt: Some(24.56),
    boil: Some( 27.07),
    electronegativity: None,
    heat_capacity: Some(1.03),
    abundance: 0.005,
    number_of_neutrons: 10,
    mass: 20.1797,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};

pub const atom_na: AtomInfo = AtomInfo {
    name: "Na",
    full_name: "Sodium",
    atomic_number: 11,
    group: 1,
    period: 3,
    density: 0.971,
    melt: Some(370.87),
    boil: Some(1156.0),
    electronegativity: Some(0.93),
    heat_capacity: Some(1.228),
    abundance: 23600.0,
    number_of_neutrons: 12,
    mass: 22.98976928,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_mg: AtomInfo = AtomInfo {
    name: "Mg",
    full_name: "Magnesium",
    atomic_number: 12,
    group: 2,
    period: 3,
    density: 1.738,
    melt: Some(923.0),
    boil: Some(1363.0),
    electronegativity: Some(1.31),
    heat_capacity: Some(1.023),
    abundance: 23300.0,
    number_of_neutrons: 12,
    mass: 24.305,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkalineEarthMetal,
};

pub const atom_al: AtomInfo = AtomInfo {
    name: "Al",
    full_name: "Aluminium",
    atomic_number: 13,
    group: 13,
    period: 3,
    density: 2.698,
    melt: Some(933.47),
    boil: Some(2792.0),
    electronegativity: Some(1.61),
    heat_capacity: Some(0.897),
    abundance: 82300.0,
    number_of_neutrons: 14,
    mass: 26.9815385,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_si: AtomInfo = AtomInfo {
    name: "Si",
    full_name: "Silicon",
    atomic_number: 14,
    group: 14,
    period: 3,
    density: 2.3296,
    melt: Some(1687.0),
    boil: Some(3538.0),
    electronegativity: Some(1.9),
    heat_capacity: Some(0.705),
    abundance: 282000.0,
    number_of_neutrons: 14,
    mass: 28.085,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_p: AtomInfo = AtomInfo {
    name: "P",
    full_name: "Phosphorus",
    atomic_number: 15,
    group: 15,
    period: 3,
    density: 1.82,
    melt: Some(317.30),
    boil: Some(550.0),
    electronegativity: Some(2.19),
    heat_capacity: Some(0.769),
    abundance: 1050.0,
    number_of_neutrons: 16,
    mass: 30.973761998,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PolyatomicNonMetal,
};

pub const atom_s: AtomInfo = AtomInfo {
    name: "S",
    full_name: "Sulfur",
    atomic_number: 16,
    group: 16,
    period: 3,
    density: 2.067,
    melt: Some(388.36),
    boil: Some(717.87),
    electronegativity: Some(2.58),
    heat_capacity: Some(0.71),
    abundance: 350.0,
    number_of_neutrons: 16,
    mass: 32.06,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PolyatomicNonMetal,
};

pub const atom_cl: AtomInfo = AtomInfo {
    name: "Cl",
    full_name: "Chlorine",
    atomic_number: 17,
    group: 17,
    period: 3,
    density: 0.003214,
    melt: Some(171.6),
    boil: Some(239.11),
    electronegativity: Some(3.16),
    heat_capacity: Some(0.479),
    abundance: 145.0,
    number_of_neutrons: 18,
    mass: 35.45,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_ar: AtomInfo = AtomInfo {
    name: "Ar",
    full_name: "Argon",
    atomic_number: 18,
    group: 18,
    period: 3,
    density: 0.0017837,
    melt: Some(83.80),
    boil: Some(87.30),
    electronegativity: None,
    heat_capacity: Some(0.52),
    abundance: 3.5,
    number_of_neutrons: 22,
    mass: 39.948,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};

pub const atom_k: AtomInfo = AtomInfo {
    name: "K",
    full_name: "Potassium",
    atomic_number: 19,
    group: 1,
    period: 4,
    density: 0.862,
    melt: Some(336.53),
    boil: Some(1032.0),
    electronegativity: Some(0.82),
    heat_capacity: Some(0.757),
    abundance: 20900.0,
    number_of_neutrons: 20,
    mass: 39.0983,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_ca: AtomInfo = AtomInfo {
    name: "Ca",
    full_name: "Calcium",
    atomic_number: 20,
    group: 2,
    period: 4,
    density: 1.54,
    melt: Some(1115.0),
    boil: Some(1757.0),
    electronegativity: Some(1.0),
    heat_capacity: Some(0.647),
    abundance: 4150.00,
    number_of_neutrons: 20,
    mass: 40.078,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkalineEarthMetal,
};

pub const atom_sc: AtomInfo = AtomInfo {
    name: "Sc",
    full_name: "Scandium",
    atomic_number: 21,
    group: 3,
    period: 4,
    density: 2.989,
    melt: Some(1814.0),
    boil: Some(3109.0),
    electronegativity: Some(1.36),
    heat_capacity: Some(0.568),
    abundance: 22.0,
    number_of_neutrons: 24,
    mass: 44.955908,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ti: AtomInfo = AtomInfo {
    name: "Ti",
    full_name: "Titanium",
    atomic_number: 22,
    group: 4,
    period: 4,
    density: 4.54,
    melt: Some(1941.0),
    boil: Some(3560.0),
    electronegativity: Some(1.54),
    heat_capacity: Some(0.523),
    abundance: 5650.0,
    number_of_neutrons: 26,
    mass: 47.867,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_v: AtomInfo = AtomInfo {
    name: "V",
    full_name: "Vanadium",
    atomic_number: 23,
    group: 5,
    period: 4,
    density: 6.11,
    melt: Some(2183.0),
    boil: Some(3680.0),
    electronegativity: Some(1.63),
    heat_capacity: Some(0.489),
    abundance: 120.0,
    number_of_neutrons: 28,
    mass: 50.9415,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_cr: AtomInfo = AtomInfo {
    name: "Cr",
    full_name: "Chromium",
    atomic_number: 24,
    group: 6,
    period: 4,
    density: 7.15,
    melt: Some(2180.0),
    boil: Some(2944.0),
    electronegativity: Some(1.66),
    heat_capacity: Some(0.449),
    abundance: 102.0,
    number_of_neutrons: 28,
    mass: 51.9961,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_mn: AtomInfo = AtomInfo {
    name: "Mn",
    full_name: "Manganese",
    atomic_number: 25,
    group: 7,
    period: 4,
    density: 7.44,
    melt: Some(1519.0),
    boil: Some(2334.0),
    electronegativity: Some(1.55),
    heat_capacity: Some(0.479),
    abundance: 950.0,
    number_of_neutrons: 30,
    mass: 54.938044,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_fe: AtomInfo = AtomInfo {
    name: "Fe",
    full_name: "Iron",
    atomic_number: 26,
    group: 8,
    period: 4,
    density: 7.874,
    melt: Some(1811.0),
    boil: Some(3134.0),
    electronegativity: Some(1.83),
    heat_capacity: Some(0.449),
    abundance: 5630.00,
    number_of_neutrons: 30,
    mass: 55.845,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_co: AtomInfo = AtomInfo {
    name: "Co",
    full_name: "Cobalt",
    atomic_number: 27,
    group: 9,
    period: 4,
    density: 8.86,
    melt: Some(1768.0),
    boil: Some(3200.0),
    electronegativity: Some(1.88),
    heat_capacity: Some(0.421),
    abundance: 25.0,
    number_of_neutrons: 32,
    mass: 58.933194,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ni: AtomInfo = AtomInfo {
    name: "Ni",
    full_name: "Nickel",
    atomic_number: 28,
    group: 10,
    period: 4,
    density: 8.912,
    melt: Some(1728.0),
    boil: Some(3186.0),
    electronegativity: Some(1.91),
    heat_capacity: Some(0.444),
    abundance: 84.0,
    number_of_neutrons: 30,
    mass: 58.6934,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_cu: AtomInfo = AtomInfo {
    name: "Cu",
    full_name: "Copper",
    atomic_number: 29,
    group: 11,
    period: 4,
    density: 8.96,
    melt: Some(1357.77),
    boil: Some(2835.0),
    electronegativity: Some(1.9),
    heat_capacity: Some(0.385),
    abundance: 60.0,
    number_of_neutrons: 34,
    mass: 63.546,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_zn: AtomInfo = AtomInfo {
    name: "Zn",
    full_name: "Zinc",
    atomic_number: 30,
    group: 12,
    period: 4,
    density: 7.134,
    melt: Some(692.88),
    boil: Some(1180.0),
    electronegativity: Some(1.65),
    heat_capacity: Some(0.388),
    abundance: 70.0,
    number_of_neutrons: 34,
    mass: 65.38,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ga: AtomInfo = AtomInfo {
    name: "Ga",
    full_name: "Gallium",
    atomic_number: 31,
    group: 13,
    period: 4,
    density: 5.907,
    melt: Some(302.9146),
    boil: Some(2673.0),
    electronegativity: Some(1.81),
    heat_capacity: Some(0.371),
    abundance: 19.0,
    number_of_neutrons: 38,
    mass: 69.723,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_ge: AtomInfo = AtomInfo {
    name: "Ge",
    full_name: "Germanium",
    atomic_number: 32,
    group: 14,
    period: 4,
    density: 5.323,
    melt: Some(1211.40),
    boil: Some(3106.0),
    electronegativity: Some(2.01),
    heat_capacity: Some(0.32),
    abundance: 1.5,
    number_of_neutrons: 42,
    mass: 72.630,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_as: AtomInfo = AtomInfo {
    name: "As",
    full_name: "Arsenic",
    atomic_number: 33,
    group: 15,
    period: 4,
    density: 5.776,
    melt: Some(1090.0),
    boil: Some(887.0),
    electronegativity: Some(2.18),
    heat_capacity: Some(0.329),
    abundance: 1.8,
    number_of_neutrons: 42,
    mass: 74.921595,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_se: AtomInfo = AtomInfo {
    name: "Se",
    full_name: "Selenium",
    atomic_number: 34,
    group: 16,
    period: 4,
    density: 4.809,
    melt: Some(453.0),
    boil: Some(958.0),
    electronegativity: Some(2.55),
    heat_capacity: Some(0.321),
    abundance: 0.05,
    number_of_neutrons: 46,
    mass: 78.971,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PolyatomicNonMetal,
};

pub const atom_br: AtomInfo = AtomInfo {
    name: "Br",
    full_name: "Bromine",
    atomic_number: 35,
    group: 17,
    period: 4,
    density: 3.122,
    melt: Some(265.8),
    boil: Some(332.0),
    electronegativity: Some(2.96),
    heat_capacity: Some(0.474),
    abundance: 2.4,
    number_of_neutrons: 44,
    mass: 79.904,
    state_of_matter: StateOfMatter::Liquid,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_kr: AtomInfo = AtomInfo {
    name: "Kr",
    full_name: "Krypton",
    atomic_number: 36,
    group: 18,
    period: 4,
    density: 0.003733,
    melt: Some(115.79),
    boil: Some(119.93),
    electronegativity: Some(3.0),
    heat_capacity: Some(0.248),
    abundance: 0.0001,
    number_of_neutrons: 48,
    mass: 83.798,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};

pub const atom_rb: AtomInfo = AtomInfo {
    name: "Rb",
    full_name: "Rubidium",
    atomic_number: 37,
    group: 1,
    period: 5,
    density: 1.532,
    melt: Some(312.46),
    boil: Some(961.0),
    electronegativity: Some(0.82),
    heat_capacity: Some(0.363),
    abundance: 90.0,
    number_of_neutrons: 48,
    mass: 85.4678,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_sr: AtomInfo = AtomInfo {
    name: "Sr",
    full_name: "Strontium",
    atomic_number: 38,
    group: 2,
    period: 5,
    density: 2.64,
    melt: Some(1050.0),
    boil: Some(1655.0),
    electronegativity: Some(0.95),
    heat_capacity: Some(0.301),
    abundance: 370.0,
    number_of_neutrons: 50,
    mass: 87.62,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkalineEarthMetal,
};

pub const atom_y: AtomInfo = AtomInfo {
    name: "Y",
    full_name: "Yttrium",
    atomic_number: 39,
    group: 3,
    period: 5,
    density: 4.469,
    melt: Some(1799.0),
    boil: Some(3609.0),
    electronegativity: Some(1.22),
    heat_capacity: Some(0.298),
    abundance: 33.0,
    number_of_neutrons: 50,
    mass: 88.90584,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_zr: AtomInfo = AtomInfo {
    name: "Zr",
    full_name: "Zirconium",
    atomic_number: 40,
    group: 4,
    period: 5,
    density: 6.506,
    melt: Some(2128.0),
    boil: Some(4682.0),
    electronegativity: Some(1.33),
    heat_capacity: Some(0.278),
    abundance: 165.0,
    number_of_neutrons: 50,
    mass: 91.224,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_nb: AtomInfo = AtomInfo {
    name: "Nb",
    full_name: "Niobium",
    atomic_number: 41,
    group: 5,
    period: 5,
    density: 8.57,
    melt: Some(2750.0),
    boil: Some(5017.0),
    electronegativity: Some(1.6),
    heat_capacity: Some(0.265),
    abundance: 20.0,
    number_of_neutrons: 52,
    mass: 92.90637,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_mo: AtomInfo = AtomInfo {
    name: "Mo",
    full_name: "Molybdenum",
    atomic_number: 42,
    group: 6,
    period: 5,
    density: 10.22,
    melt: Some(2896.0),
    boil: Some(4912.0),
    electronegativity: Some(2.16),
    heat_capacity: Some(0.251),
    abundance: 1.2,
    number_of_neutrons: 56,
    mass: 95.95,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_tc: AtomInfo = AtomInfo {
    name: "Tc",
    full_name: "Technetium",
    atomic_number: 43,
    group: 7,
    period: 5,
    density: 11.5,
    melt: Some(2430.0),
    boil: Some(4538.0),
    electronegativity: Some(1.9),
    heat_capacity: None,
    abundance: 0.000000003,
    number_of_neutrons: 55,
    mass: 98.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ru: AtomInfo = AtomInfo {
    name: "Ru",
    full_name: "Ruthenium",
    atomic_number: 44,
    group: 8,
    period: 5,
    density: 12.37,
    melt: Some(2607.0),
    boil: Some(4423.0),
    electronegativity: Some(2.2),
    heat_capacity: Some(0.238),
    abundance: 0.001,
    number_of_neutrons: 58,
    mass: 101.07,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_rh: AtomInfo = AtomInfo {
    name: "Rh",
    full_name: "Rhodium",
    atomic_number: 45,
    group: 9,
    period: 5,
    density: 12.41,
    melt: Some(2237.0),
    boil: Some(3968.0),
    electronegativity: Some(2.28),
    heat_capacity: Some(0.243),
    abundance: 0.001,
    number_of_neutrons: 58,
    mass: 102.90550,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_pd: AtomInfo = AtomInfo {
    name: "Pd",
    full_name: "Palladium",
    atomic_number: 46,
    group: 10,
    period: 5,
    density: 12.02,
    melt: Some(1828.05),
    boil: Some(3236.0),
    electronegativity: Some(2.2),
    heat_capacity: Some(0.244),
    abundance: 0.015,
    number_of_neutrons: 62,
    mass: 106.42,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ag: AtomInfo = AtomInfo {
    name: "Ag",
    full_name: "Silver",
    atomic_number: 47,
    group: 11,
    period: 5,
    density: 10.501,
    melt: Some(1234.93),
    boil: Some(2435.0),
    electronegativity: Some(1.93),
    heat_capacity: Some(0.235),
    abundance: 0.075,
    number_of_neutrons: 60,
    mass: 107.8682,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_cd: AtomInfo = AtomInfo {
    name: "Cd",
    full_name: "Cadmium",
    atomic_number: 48,
    group: 12,
    period: 5,
    density: 8.69,
    melt: Some(594.22),
    boil: Some(1040.0),
    electronegativity: Some(1.69),
    heat_capacity: Some(0.232),
    abundance: 0.159,
    number_of_neutrons: 66,
    mass: 112.414,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_in: AtomInfo = AtomInfo {
    name: "In",
    full_name: "Indium",
    atomic_number: 49,
    group: 13,
    period: 5,
    density: 7.31,
    melt: Some(429.75),
    boil: Some(2345.0),
    electronegativity: Some(1.78),
    heat_capacity: Some(0.233),
    abundance: 0.25,
    number_of_neutrons: 66,
    mass: 114.818,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_sn: AtomInfo = AtomInfo {
    name: "Sn",
    full_name: "Tin",
    atomic_number: 50,
    group: 14,
    period: 5,
    density: 7.287,
    melt: Some(505.08),
    boil: Some(2875.0),
    electronegativity: Some(1.96),
    heat_capacity: Some(0.228),
    abundance: 2.3,
    number_of_neutrons: 70,
    mass: 118.710,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_sb: AtomInfo = AtomInfo {
    name: "Sb",
    full_name: "Antimony",
    atomic_number: 51,
    group: 15,
    period: 5,
    density: 6.685,
    melt: Some(903.78),
    boil: Some(1860.0),
    electronegativity: Some(2.05),
    heat_capacity: Some(0.207),
    abundance: 0.2,
    number_of_neutrons: 70,
    mass: 121.760,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_te: AtomInfo = AtomInfo {
    name: "Te",
    full_name: "Tellurium",
    atomic_number: 52,
    group: 16,
    period: 5,
    density: 6.232,
    melt: Some(722.66),
    boil: Some(1261.0),
    electronegativity: Some(2.1),
    heat_capacity: Some(0.202),
    abundance: 0.001,
    number_of_neutrons: 74,
    mass: 127.60,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_i: AtomInfo = AtomInfo {
    name: "I",
    full_name: "Iodine",
    atomic_number: 53,
    group: 17,
    period: 5,
    density: 4.93,
    melt: Some(386.85),
    boil: Some(457.4),
    electronegativity: Some(2.66),
    heat_capacity: Some(0.214),
    abundance: 0.45,
    number_of_neutrons: 74,
    mass: 126.90447,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::DiatomicNonMetal,
};

pub const atom_xe: AtomInfo = AtomInfo {
    name: "Xe",
    full_name: "Xenon",
    atomic_number: 54,
    group: 18,
    period: 5,
    density: 0.005887,
    melt: Some(161.4),
    boil: Some(165.03),
    electronegativity: Some(2.6),
    heat_capacity: Some(0.158),
    abundance: 0.00003,
    number_of_neutrons: 78,
    mass: 131.293,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};

pub const atom_cs: AtomInfo = AtomInfo {
    name: "Cs",
    full_name: "Caesium",
    atomic_number: 55,
    group: 1,
    period: 6,
    density: 1.873,
    melt: Some(301.59),
    boil: Some(944.0),
    electronegativity: Some(0.79),
    heat_capacity: Some(0.242),
    abundance: 3.0,
    number_of_neutrons: 78,
    mass: 132.90545196,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_ba: AtomInfo = AtomInfo {
    name: "Ba",
    full_name: "Barium",
    atomic_number: 56,
    group: 2,
    period: 6,
    density: 3.594,
    melt: Some(1000.0),
    boil: Some(2170.0),
    electronegativity: Some(0.89),
    heat_capacity: Some(0.204),
    abundance: 425.0,
    number_of_neutrons: 82,
    mass: 137.327,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkalineEarthMetal,
};

pub const atom_la: AtomInfo = AtomInfo {
    name: "La",
    full_name: "Lanthanum",
    atomic_number: 57,
    group: 3,
    period: 6,
    density: 6.145,
    melt: Some(1193.0),
    boil: Some(3737.0),
    electronegativity: Some(1.1),
    heat_capacity: Some(0.195),
    abundance: 39.0,
    number_of_neutrons: 82,
    mass: 138.90547,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_ce: AtomInfo = AtomInfo {
    name: "Ce",
    full_name: "Cerium",
    atomic_number: 58,
    period: 6,
    group: 0,
    density: 6.77,
    melt: Some(1068.0),
    boil: Some(3716.0),
    electronegativity: Some(1.12),
    heat_capacity: Some(0.192),
    abundance: 66.5,
    number_of_neutrons: 82,
    mass: 140.116,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_pr: AtomInfo = AtomInfo {
    name: "Pr",
    full_name: "Praseodymium",
    atomic_number: 59,
    period: 6,
    group: 0,
    density: 6.773,
    melt: Some(1208.0),
    boil: Some(3793.0),
    electronegativity: Some(1.13),
    heat_capacity: Some(0.193),
    abundance: 9.2,
    number_of_neutrons: 82,
    mass: 140.90766,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_nd: AtomInfo = AtomInfo {
    name: "Nd",
    full_name: "Neodymium",
    atomic_number: 60,
    period: 6,
    group: 0,
    density: 7.007,
    melt: Some(1297.0),
    boil: Some(3347.0),
    electronegativity: Some(1.14),
    heat_capacity: Some(0.19),
    abundance: 41.5,
    number_of_neutrons: 82,
    mass: 144.242,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_pm: AtomInfo = AtomInfo {
    name: "Pm",
    full_name: "Promethium",
    atomic_number: 61,
    period: 6,
    group: 0,
    density: 7.26,
    melt: Some(1315.0),
    boil: Some(3273.0),
    electronegativity: Some(1.13),
    heat_capacity: None,
    abundance: 0.0000000000000000002,
    number_of_neutrons: 84,
    mass: 145.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_sm: AtomInfo = AtomInfo {
    name: "Sm",
    full_name: "Samarium",
    atomic_number: 62,
    period: 6,
    group: 0,
    density: 7.52,
    melt: Some(1345.0),
    boil: Some(2067.0),
    electronegativity: Some(1.17),
    heat_capacity: Some(0.197),
    abundance: 7.05,
    number_of_neutrons: 90,
    mass: 150.36,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_eu: AtomInfo = AtomInfo {
    name: "Eu",
    full_name: "Europium",
    atomic_number: 63,
    period: 6,
    group: 0,
    density: 5.243,
    melt: Some(1099.0),
    boil: Some(1802.0),
    electronegativity: Some(1.2),
    heat_capacity: Some(0.182),
    abundance: 2.0,
    number_of_neutrons: 90,
    mass: 151.964,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_gd: AtomInfo = AtomInfo {
    name: "Gd",
    full_name: "Gadolinium",
    atomic_number: 64,
    period: 6,
    group: 0,
    density: 7.895,
    melt: Some(1585.0),
    boil: Some(3546.0),
    electronegativity: Some(1.2),
    heat_capacity: Some(0.236),
    abundance: 6.2,
    number_of_neutrons: 94,
    mass: 157.25,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_tb: AtomInfo = AtomInfo {
    name: "Tb",
    full_name: "Terbium",
    atomic_number: 65,
    period: 6,
    group: 0,
    density: 8.229,
    melt: Some(1629.0),
    boil: Some(3503.0),
    electronegativity: Some(1.2),
    heat_capacity: Some(0.182),
    abundance: 1.2,
    number_of_neutrons: 94,
    mass: 158.92535,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_dy: AtomInfo = AtomInfo {
    name: "Dy",
    full_name: "Dysprosium",
    atomic_number: 66,
    period: 6,
    group: 0,
    density: 8.55,
    melt: Some(1680.0),
    boil: Some(2840.0),
    electronegativity: Some(1.22),
    heat_capacity: Some(0.17),
    abundance: 5.2,
    number_of_neutrons: 98,
    mass: 162.500,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_ho: AtomInfo = AtomInfo {
    name: "Ho",
    full_name: "Holmium",
    atomic_number: 67,
    period: 6,
    group: 0,
    density: 8.795,
    melt: Some(1734.0),
    boil: Some(2993.0),
    electronegativity: Some(1.23),
    heat_capacity: Some(0.165),
    abundance: 1.3,
    number_of_neutrons: 98,
    mass: 164.93033,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_er: AtomInfo = AtomInfo {
    name: "Er",
    full_name: "Erbium",
    atomic_number: 68,
    period: 6,
    group: 0,
    density: 9.066,
    melt: Some(1802.0),
    boil: Some(3141.0),
    electronegativity: Some(1.24),
    heat_capacity: Some(0.168),
    abundance: 3.5,
    number_of_neutrons: 98,
    mass: 167.259,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_tm: AtomInfo = AtomInfo {
    name: "Tm",
    full_name: "Thulium",
    atomic_number: 69,
    period: 6,
    group: 0,
    density: 9.321,
    melt: Some(1818.0),
    boil: Some(2223.0),
    electronegativity: Some(1.25),
    heat_capacity: Some(0.16),
    abundance: 0.52,
    number_of_neutrons: 100,
    mass: 168.93422,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_yb: AtomInfo = AtomInfo {
    name: "Yb",
    full_name: "Ytterbium",
    atomic_number: 70,
    period: 6,
    group: 0,
    density: 6.965,
    melt: Some(1097.0),
    boil: Some(1469.0),
    electronegativity: Some(1.1),
    heat_capacity: Some(0.155),
    abundance: 3.2,
    number_of_neutrons: 104,
    mass: 173.045,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_lu: AtomInfo = AtomInfo {
    name: "Lu",
    full_name: "Lutetium",
    atomic_number: 71,
    period: 6,
    group: 0,
    density: 9.84,
    melt: Some(1925.0),
    boil: Some(3675.0),
    electronegativity: Some(1.27),
    heat_capacity: Some(0.154),
    abundance: 0.8,
    number_of_neutrons: 104,
    mass: 174.9668,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Lanthanide,
};

pub const atom_hf: AtomInfo = AtomInfo {
    name: "Hf",
    full_name: "Hafnium",
    atomic_number: 72,
    group: 4,
    period: 6,
    density: 13.31,
    melt: Some(2506.0),
    boil: Some(4876.0),
    electronegativity: Some(1.3),
    heat_capacity: Some(0.144),
    abundance: 3.0,
    number_of_neutrons: 108,
    mass: 178.49,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ta: AtomInfo = AtomInfo {
    name: "Ta",
    full_name: "Tantalum",
    atomic_number: 73,
    group: 5,
    period: 6,
    density: 16.654,
    melt: Some(3290.0),
    boil: Some(5731.0),
    electronegativity: Some(1.5),
    heat_capacity: Some(0.14),
    abundance: 2.0,
    number_of_neutrons: 108,
    mass: 180.94788,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_w: AtomInfo = AtomInfo {
    name: "W",
    full_name: "Tungsten",
    atomic_number: 74,
    group: 6,
    period: 6,
    density: 19.25,
    melt: Some(3695.0),
    boil: Some(5828.0),
    electronegativity: Some(2.36),
    heat_capacity: Some(0.132),
    abundance: 1.3,
    number_of_neutrons: 110,
    mass: 183.84,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_re: AtomInfo = AtomInfo {
    name: "Re",
    full_name: "Rhenium",
    atomic_number: 75,
    group: 7,
    period: 6,
    density: 21.02,
    melt: Some(3459.0),
    boil: Some(5869.0),
    electronegativity: Some(1.9),
    heat_capacity: Some(0.137),
    abundance: 0.0007,
    number_of_neutrons: 110,
    mass: 186.207,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_os: AtomInfo = AtomInfo {
    name: "Os",
    full_name: "Osmium",
    atomic_number: 76,
    group: 8,
    period: 6,
    density: 22.61,
    melt: Some(3306.0),
    boil: Some(5285.0),
    electronegativity: Some(2.2),
    heat_capacity: Some(0.13),
    abundance: 0.002,
    number_of_neutrons: 116,
    mass: 190.23,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ir: AtomInfo = AtomInfo {
    name: "Ir",
    full_name: "Iridium",
    atomic_number: 77,
    group: 9,
    period: 6,
    density: 22.56,
    melt: Some(2719.0),
    boil: Some(4701.0),
    electronegativity: Some(2.2),
    heat_capacity: Some(0.131),
    abundance: 0.001,
    number_of_neutrons: 116,
    mass: 192.217,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_pt: AtomInfo = AtomInfo {
    name: "Pt",
    full_name: "Platinum",
    atomic_number: 78,
    group: 10,
    period: 6,
    density: 21.46,
    melt: Some(2041.4),
    boil: Some(4098.0),
    electronegativity: Some(2.28),
    heat_capacity: Some(0.133),
    abundance: 0.005,
    number_of_neutrons: 117,
    mass: 195.084,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_au: AtomInfo = AtomInfo {
    name: "Au",
    full_name: "Gold",
    atomic_number: 79,
    group: 11,
    period: 6,
    density: 19.282,
    melt: Some(1337.33),
    boil: Some(3129.0),
    electronegativity: Some(2.54),
    heat_capacity: Some(0.129),
    abundance: 0.004,
    number_of_neutrons: 118,
    mass: 196.966569,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_hg: AtomInfo = AtomInfo {
    name: "Hg",
    full_name: "Mercury",
    atomic_number: 80,
    group: 12,
    period: 6,
    density: 13.5336,
    melt: Some(234.43),
    boil: Some(629.88),
    electronegativity: Some(2.0),
    heat_capacity: Some(0.14),
    abundance: 0.085,
    number_of_neutrons: 122,
    mass: 200.592,
    state_of_matter: StateOfMatter::Liquid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_tl: AtomInfo = AtomInfo {
    name: "Tl",
    full_name: "Thallium",
    atomic_number: 81,
    group: 13,
    period: 6,
    density: 11.85,
    melt: Some(577.0),
    boil: Some(1746.0),
    electronegativity: Some(1.62),
    heat_capacity: Some(0.129),
    abundance: 0.85,
    number_of_neutrons: 124,
    mass: 204.38,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_pb: AtomInfo = AtomInfo {
    name: "Pb",
    full_name: "Lead",
    atomic_number: 82,
    group: 14,
    period: 6,
    density: 11.342,
    melt: Some(600.61),
    boil: Some(2022.0),
    electronegativity: Some(1.87),
    heat_capacity: Some(0.129),
    abundance: 14.0,
    number_of_neutrons: 126,
    mass: 207.2,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_bi: AtomInfo = AtomInfo {
    name: "Bi",
    full_name: "Bismuth",
    atomic_number: 83,
    group: 15,
    period: 6,
    density: 9.807,
    melt: Some(544.7),
    boil: Some(1837.0),
    electronegativity: Some(2.02),
    heat_capacity: Some(0.122),
    abundance: 0.009,
    number_of_neutrons: 126,
    mass: 208.98040,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_po: AtomInfo = AtomInfo {
    name: "Po",
    full_name: "Polonium",
    atomic_number: 84,
    group: 16,
    period: 6,
    density: 9.32,
    melt: Some(527.0),
    boil: Some(1235.0),
    electronegativity: Some(2.0),
    heat_capacity: None,
    abundance: 0.0000000002,
    number_of_neutrons: 125,
    mass: 209.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_at: AtomInfo = AtomInfo {
    name: "At",
    full_name: "Astatine",
    atomic_number: 85,
    group: 17,
    period: 6,
    density: 7.0,
    melt: Some(575.0),
    boil: Some(610.0),
    electronegativity: Some(2.2),
    heat_capacity: None,
    abundance: 0.000000000000000000003,
    number_of_neutrons: 125,
    mass: 210.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Metalloid,
};

pub const atom_rn: AtomInfo = AtomInfo {
    name: "Rn",
    full_name: "Radon",
    atomic_number: 86,
    group: 18,
    period: 6,
    density: 0.00973,
    melt: Some(202.0),
    boil: Some(211.3),
    electronegativity: Some(2.2),
    heat_capacity: Some(0.094),
    abundance: 0.0000000000004,
    number_of_neutrons: 136,
    mass: 222.0,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::NobleGas,
};

pub const atom_fr: AtomInfo = AtomInfo {
    name: "Fr",
    full_name: "Francium",
    atomic_number: 87,
    group: 1,
    period: 7,
    density: 1.87,
    melt: Some(300.0),
    boil: Some(950.0),
    electronegativity: Some(0.7),
    heat_capacity: None,
    abundance: 0.000000000000000001,
    number_of_neutrons: 136,
    mass: 223.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_ra: AtomInfo = AtomInfo {
    name: "Ra",
    full_name: "Radium",
    atomic_number: 88,
    period: 7,
    density: 5.5,
    melt: Some(973.0),
    boil: Some(2010.0),
    electronegativity: Some(0.9),
    heat_capacity: Some(0.094),
    abundance: 0.0000009,
    group: 2,
    number_of_neutrons: 138,
    mass: 226.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::AlkaliMetal,
};

pub const atom_ac: AtomInfo = AtomInfo {
    name: "Ac",
    full_name: "Actinium",
    atomic_number: 89,
    period: 7,
    density: 10.07,
    melt: Some(1323.0),
    boil: Some(3471.0),
    electronegativity: Some(1.1),
    heat_capacity: Some(0.12),
    abundance: 0.00000000055,
    group: 3,
    number_of_neutrons: 138,
    mass: 227.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_th: AtomInfo = AtomInfo {
    name: "Th",
    full_name: "Thorium",
    atomic_number: 90,
    period: 7,
    group: 0,
    density: 11.72,
    melt: Some(2115.0),
    boil: Some(5061.0),
    electronegativity: Some(1.3),
    heat_capacity: Some(0.113),
    abundance: 9.6,
    number_of_neutrons: 142,
    mass: 232.0377,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_pa: AtomInfo = AtomInfo {
    name: "Pa",
    full_name: "Protactinium",
    atomic_number: 91,
    period: 7,
    group: 0,
    density: 15.37,
    melt: Some(1841.0),
    boil: Some(4300.0),
    electronegativity: Some(1.5),
    heat_capacity: None,
    abundance: 0.0000014,
    number_of_neutrons: 140,
    mass: 231.036,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_u: AtomInfo = AtomInfo {
    name: "U",
    full_name: "Uranium",
    atomic_number: 92,
    period: 7,
    group: 0,
    density: 18.95,
    melt: Some(1405.3),
    boil: Some(4404.0),
    electronegativity: Some(1.38),
    heat_capacity: Some(0.116),
    abundance: 2.7,
    number_of_neutrons: 147,
    mass: 238.02891,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_np: AtomInfo = AtomInfo {
    name: "Np",
    full_name: "Neptunium",
    atomic_number: 93,
    period: 7,
    group: 0,
    density: 20.45,
    melt: Some(917.0),
    boil: Some(4273.0),
    electronegativity: Some(1.36),
    heat_capacity: None,
    abundance: 0.000000000003,
    number_of_neutrons: 144,
    mass: 237.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_pu: AtomInfo = AtomInfo {
    name: "Pu",
    full_name: "Plutonium",
    atomic_number: 94,
    period: 7,
    group: 0,
    density: 19.84,
    melt: Some(912.5),
    boil: Some(3501.0),
    electronegativity: Some(1.28),
    heat_capacity: None,
    abundance: 0.00000000003,
    number_of_neutrons: 150,
    mass: 244.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_am: AtomInfo = AtomInfo {
    name: "Am",
    full_name: "Americium",
    atomic_number: 95,
    period: 7,
    group: 0,
    density: 13.69,
    melt: Some(1449.0),
    boil: Some(2880.0),
    electronegativity: Some(1.13),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 148,
    mass: 243.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_cm: AtomInfo = AtomInfo {
    name: "Cm",
    full_name: "Curium",
    atomic_number: 96,
    period: 7,
    group: 0,
    density: 13.51,
    melt: Some(1613.0),
    boil: Some(3383.0),
    electronegativity: Some(1.28),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 151,
    mass: 247.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_bk: AtomInfo = AtomInfo {
    name: "Bk",
    full_name: "Berkelium",
    atomic_number: 97,
    period: 7,
    group: 0,
    density: 14.79,
    melt: Some(1259.0),
    boil: Some(2900.0),
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 150,
    mass: 247.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_cf: AtomInfo = AtomInfo {
    name: "Cf",
    full_name: "Californium",
    atomic_number: 98,
    period: 7,
    group: 0,
    density: 15.1,
    melt: Some(1173.0),
    boil: Some(1743.0),
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 153,
    mass: 251.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_es: AtomInfo = AtomInfo {
    name: "Es",
    full_name: "Einsteinium",
    atomic_number: 99,
    period: 7,
    group: 0,
    density: 8.84,
    melt: Some(1133.0),
    boil: Some(1269.0),
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 153,
    mass: 252.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_fm: AtomInfo = AtomInfo {
    name: "Fm",
    full_name: "Fermium",
    atomic_number: 100,
    period: 7,
    group: 0,
    density: 9.7,
    melt: Some(1125.0),
    boil: None,
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 157,
    mass: 257.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_md: AtomInfo = AtomInfo {
    name: "Md",
    full_name: "Mendelevium",
    atomic_number: 101,
    period: 7,
    group: 0,
    density: 10.3,
    melt: Some(1100.0),
    boil: None,
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 157,
    mass: 258.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_no: AtomInfo = AtomInfo {
    name: "No",
    full_name: "Nobelium",
    atomic_number: 102,
    period: 7,
    group: 0,
    density: 9.9,
    melt: Some(1100.0),
    boil: None,
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 157,
    mass: 259.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_lr: AtomInfo = AtomInfo {
    name: "Lr",
    full_name: "Lawrencium",
    atomic_number: 103,
    period: 7,
    group: 0,
    density: 15.6,
    melt: Some(1900.0),
    boil: None,
    electronegativity: Some(1.3),
    heat_capacity: None,
    abundance: 0.0,
    number_of_neutrons: 159,
    mass: 262.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Actinide,
};

pub const atom_rf: AtomInfo = AtomInfo {
    name: "Rf",
    full_name: "Rutherfordium",
    atomic_number: 104,
    period: 7,
    density: 23.2,
    melt: Some(2400.0),
    boil: Some(5800.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 4,
    number_of_neutrons: 157,
    mass: 261.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_db: AtomInfo = AtomInfo {
    name: "Db",
    full_name: "Dubnium",
    atomic_number: 105,
    period: 7,
    density: 29.3,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 5,
    number_of_neutrons: 157,
    mass: 262.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_sg: AtomInfo = AtomInfo {
    name: "Sg",
    full_name: "Seaborgium",
    atomic_number: 106,
    period: 7,
    density: 35.0,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 6,
    number_of_neutrons: 157,
    mass: 263.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_bh: AtomInfo = AtomInfo {
    name: "Bh",
    full_name: "Bohrium",
    atomic_number: 107,
    period: 7,
    density: 37.1,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 7,
    number_of_neutrons: 155,
    mass: 155.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_hs: AtomInfo = AtomInfo {
    name: "Hs",
    full_name: "Hassium",
    atomic_number: 108,
    period: 7,
    density: 40.7,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 8,
    number_of_neutrons: 157,
    mass: 265.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_mt: AtomInfo = AtomInfo {
    name: "Mt",
    full_name: "Meitnerium",
    atomic_number: 109,
    period: 7,
    density: 37.4,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 9,
    number_of_neutrons: 157,
    mass: 266.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_ds: AtomInfo = AtomInfo {
    name: "Ds",
    full_name: "Darmstadtium",
    atomic_number: 110,
    period: 7,
    density: 34.8,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 10,
    number_of_neutrons: 151,
    mass: 281.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_rg: AtomInfo = AtomInfo {
    name: "Rg",
    full_name: "Roentgenium",
    atomic_number: 111,
    period: 7,
    density: 28.7,
    melt: None,
    boil: None,
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 11,
    number_of_neutrons: 161,
    mass: 280.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_cn: AtomInfo = AtomInfo {
    name: "Cn",
    full_name: "Copernicium",
    atomic_number: 112,
    period: 7,
    density: 23.7,
    melt: None,
    boil: Some(357.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 12,
    number_of_neutrons: 173,
    mass: 285.0,
    state_of_matter: StateOfMatter::Gas,
    sub_category: SubCategory::TransitionMetal,
};

pub const atom_nh: AtomInfo = AtomInfo {
    name: "Nh",
    full_name: "Nihonium",
    atomic_number: 113,
    period: 7,
    density: 16.0,
    melt: Some(700.0),
    boil: Some(1400.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 13,
    number_of_neutrons: 173,
    mass: 113.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_fl: AtomInfo = AtomInfo {
    name: "Fl",
    full_name: "Flerovium",
    atomic_number: 114,
    period: 7,
    density: 14.0,
    melt: Some(340.0),
    boil: Some(420.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 14,
    number_of_neutrons: 175,
    mass: 289.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::PostTransitionMetal,
};

pub const atom_mc: AtomInfo = AtomInfo {
    name: "Mc",
    full_name: "Moscovium",
    atomic_number: 115,
    period: 7,
    density: 13.5,
    melt: Some(700.0),
    boil: Some(1400.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 15,
    number_of_neutrons: 174,
    mass: 290.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_lv: AtomInfo = AtomInfo {
    name: "Lv",
    full_name: "Livermorium",
    atomic_number: 116,
    period: 7,
    density: 12.9,
    melt: Some(709.0),
    boil: Some(1085.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 16,
    number_of_neutrons: 177,
    mass: 293.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_ts: AtomInfo = AtomInfo {
    name: "Ts",
    full_name: "Tennessine",
    atomic_number: 117,
    period: 7,
    density: 7.2,
    melt: Some(723.0),
    boil: Some(883.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 17,
    number_of_neutrons: 177,
    mass: 294.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};

pub const atom_og: AtomInfo = AtomInfo {
    name: "Og",
    full_name: "Oganesson",
    atomic_number: 118,
    period: 7,
    density: 5.0,
    melt: Some(258.0),
    boil: Some(263.0),
    electronegativity: None,
    heat_capacity: None,
    abundance: 0.0,
    group: 18,
    number_of_neutrons: 176,
    mass: 294.0,
    state_of_matter: StateOfMatter::Solid,
    sub_category: SubCategory::Unknown,
};
